@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

title Components für Container Activity Sampling

Person(softwareDeveloper, "Softwareentwickler", "Ein Softwareentwickler möchte den Aufwand für seine Aufgaben dokumentieren.")
Container_Boundary(activitySamplingContainer, "Activity Sampling") {
  Component(activitySampling, "Activity Sampling", "Java, JavaFX", "Integriert Backend und Frontend.")
  Component(activitySamplingFrontend, "Activity Sampling Frontend", "Java, JavaFX", "Erzeugt Commands und Queries and stellt Query Results dar.")
  Component(activitySamplingBackend, "Activity Sampling Backend", "Java", "Verarbeitet Commands, Queries und Notfications. Liefert Command Status und Query Results.")
  Component(activitySamplingContract, "Activity Sampling Contract", "Java", "Definiert Commands, Queries, Notfications und allgemeine Daten.")
}
ContainerDb(filesystem, "Dateisystem", "Enthält Aktivitäten in einer CSV-Datei.")

Rel(softwareDeveloper, activitySampling, "Protokolliert Aktivitäten", "JavaFX")
Rel(activitySampling, activitySamplingFrontend, "Integriert", "Java, Library")
Rel(activitySampling, activitySamplingBackend, "Integriert", "Java, Library")
Rel(activitySamplingBackend, activitySamplingContract, "Nutzt", "Java, Library")
Rel(activitySamplingFrontend, activitySamplingContract, "Nutzt", "Java, Library")
Rel(activitySamplingBackend, filesystem, Sichert Aktivitäten", "CSV-Datei")
@enduml
