@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

title Containers für System Activity Sampling

Person(softwareDeveloper, "Softwareentwickler", "Ein Softwareentwickler möchte den Aufwand für seine Aufgaben dokumentieren.")
System_Boundary(activitySamplingSystem, "Activity Sampling") {
  Container(activitySamplingApp, "Activity Sampling", "Java, JavaFX", "Erlaubt dem Nutzer das Protokollieren seiner Aktivitäten.")
  ContainerDb(filesystem, "Dateisystem", "Enthält Aktivitäten in einer CSV-Datei.")
}

Rel(softwareDeveloper, activitySamplingApp, "Protokolliert Aktivitäten", "GUI")
Rel(activitySamplingApp, filesystem, "Sichert Aktivitäten", "CSV-Datei")
@enduml
